$fontFamily = PoiretOne

general {
    disable_loading_bar = false
    grace = 0
    hide_cursor = false
    no_fade_in = false
}

background {
    monitor =
    path = ~/Pictures/wallpapers/clouds.jpg
    blur_passes = 2
    blur_size = 5
}

# BACKGROUND SHAPE
shape {
    monitor =
    size = 30%, 100%
    color = rgba(17, 17, 17, 0.29)
    rounding = 0
    halign = left
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12
    text_align = left
    color = rgba(255, 255, 255, 1.0)
    font_family = $fontFamily
    font_size = 90
    position = 5%, -10%
    halign = left
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B %Y"
    color = rgb(255, 255, 255)
    font_size = 30
    font_family = $fontFamily
    position = 5%, -20%
    halign = left
    valign = top
}

# USER ICON
image {
    monitor =
    path = ~/Pictures/icons/fern1x1.jpg
    size = 300
    rounding = -1
    position = 10%, 100
    halign = left
    valign = center
}

# USER NAME
shape {
    monitor =
    size = 20%, 50
    color = rgba(0, 0, 0, 0.5)
    rounding = -1
    position = 5%, -150
    halign = left
    valign = center
}
label {
    monitor =
    text = $USER
    text_align = center
    color = rgba(255, 255, 255, 1)
    font_family = $fontFamily
    font_size = 25
    position = 14%, -150
    halign = left
    valign = center
}

# PASSWORD FIELD
input-field {
    monitor =
    fade_on_empty = false
    size = 20%, 50
    rounding = -1
    position = 5%, -250
    halign = left
    valign = center
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.1
    font_family = $fontFamily
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(255, 255, 255)
    check_color = rgb(139, 85, 255)
    check_text = <i>Authenticating...</i>
    fail_color = rgba(255, 0, 0, 0.5)
    fail_text = <i>Access Denied</i>
    placeholder_text = <i>Password </i>
}