general {
    lock_cmd = pidof hyprlock || hyprlock           # avoids launching multiple hyprlock instances
    before_sleep_cmd = pidof hyprlock || hyprlock   # lockscreen
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'      # turn monitor back on
    ignore_wayland_inhibit = true
}

listener {
    timeout = 300                                   # 5 mins
    on-timeout = pidof hyprlock || hyprlock         # lockscreen
    condition_cmd = ~/dotfiles/hypr/can-suspend.sh  # run script to check if a video is playing
}

listener {
    timeout = 420                                                           # 7 mins
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'         # display off
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'           # display on
    condition_cmd = ~/dotfiles/hypr/can-dpms-off.sh                         # run script to check if a video is playing
    condition_retry = 5
}