general {
    lock_cmd = pidof hyprlock || hyprlock           # avoids launching multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session        # lockscreen
    after_sleep_cmd = hyprctl dispatch dpms on      # turn monitor back on
}

listener {
    timeout = 300                                   # 5 mins
    on-timeout = loginctl lock-session              # lockscreen
}

listener {
    timeout = 420                                   # 7 mins
    on-timeout = hyprctl dispatch dpms off          # display off
    on-resume = hyprctl dispatch dpms on            # ddisplay on
}